using System.IO;
using aoc2018.Code;
using Xunit;
using Xunit.Abstractions;

namespace aoc2018.Test
{
    public class Test17
    {
        private readonly ITestOutputHelper _output;

        #region Inputs
        private const string Input = @"
x=495, y=2..7
y=7, x=495..501
x=501, y=3..7
x=498, y=2..4
x=506, y=1..2
x=498, y=10..13
x=504, y=10..13
y=13, x=498..504";

        private const string Map = @"
......+.......
............#.
.#..#.......#.
.#..#..#......
.#..#..#......
.#.....#......
.#.....#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...";

        private const string WateredMap5 = @"
......+.......
......|.....#.
.#..#.|.....#.
.#..#.|#......
.#..#.|#......
.#....|#......
.#~~~~~#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...";

        private const string WateredMap10 = @"
......+.......
......|.....#.
.#..#.|.....#.
.#..#.|#......
.#..#.|#......
.#~~~~~#......
.#~~~~~#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...";

        private const string WateredMap14 = @"
......+.......
......|.....#.
.#..#.|.....#.
.#..#~~#......
.#..#~~#......
.#~~~~~#......
.#~~~~~#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...";

        private const string WateredMap19 = @"
......+.......
......|.....#.
.#..#||||...#.
.#..#~~#|.....
.#..#~~#|.....
.#~~~~~#|.....
.#~~~~~#|.....
.#######|.....
........|.....
........|.....
....#...|.#...
....#...|.#...
....#~~~~~#...
....#######...";

        private const string WateredMap29 = @"
......+.......
......|.....#.
.#..#||||...#.
.#..#~~#|.....
.#..#~~#|.....
.#~~~~~#|.....
.#~~~~~#|.....
.#######|.....
........|.....
........|.....
....#~~~~~#...
....#~~~~~#...
....#~~~~~#...
....#######...";
        
        private const string WateredMap30 = @"
......+.......
......|.....#.
.#..#||||...#.
.#..#~~#|.....
.#..#~~#|.....
.#~~~~~#|.....
.#~~~~~#|.....
.#######|.....
........|.....
...|||||||||..
...|#~~~~~#|..
...|#~~~~~#|..
...|#~~~~~#|..
...|#######|..";

        private const string FullyWateredMap = @"
......+.......
......|.....#.
.#..#||||...#.
.#..#~~#|.....
.#..#~~#|.....
.#~~~~~#|.....
.#~~~~~#|.....
.#######|.....
........|.....
...|||||||||..
...|#~~~~~#|..
...|#~~~~~#|..
...|#~~~~~#|..
...|#######|..";

        #endregion

        public Test17(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void Parse()
        {
            
            var scan = Day17.Parse(Input.Trim());
            var map = Day17.Print(scan);
            Assert.Equal(Map.Trim(), map.Trim());
        }

        [Theory]
        [InlineData(5, WateredMap5)]
        [InlineData(10, WateredMap10)]
        [InlineData(14, WateredMap14)]
        [InlineData(19, WateredMap19)]
        [InlineData(29, WateredMap29)]
        [InlineData(30, WateredMap30)]
        [InlineData(null, FullyWateredMap)]
        public void Test(int? drops, string expected)
        {
            var scan = Day17.Parse(Input.Trim());
            var (wateredScan, _) = Day17.Pour(scan, drops);
            var wateredMap = Day17.Print(wateredScan);
            Assert.Equal(expected.Trim(), wateredMap.Trim());
        }

        [Fact]
        public void Solve1()
        {
            var input = File.ReadAllText("C:\\Code\\aoc2018\\aoc2018\\Data\\input17.txt");
            var scan = Day17.Parse(input.Trim());
            var result = Day17.Pour(scan, null);
            _output.WriteLine(result.watercount.ToString());
        }
    }
}
